theme: jekyll-theme-minimal
title: Open Source @ METRC
description: Open Source software from the Major Extremity Trauma Research Consortium (METRC) at the Johns Hopkins Bloomberg School of Public Health
